/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SupplyChain {
  export type DonationStruct = {
    donationId: string;
    donor: AddressLike;
    amount: BigNumberish;
    purpose: string;
    timestamp: BigNumberish;
    isUsed: boolean;
  };

  export type DonationStructOutput = [
    donationId: string,
    donor: string,
    amount: bigint,
    purpose: string,
    timestamp: bigint,
    isUsed: boolean
  ] & {
    donationId: string;
    donor: string;
    amount: bigint;
    purpose: string;
    timestamp: bigint;
    isUsed: boolean;
  };
}

export interface SupplyChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "createItem"
      | "donations"
      | "getDonation"
      | "itemCount"
      | "items"
      | "recordDonation"
      | "updateItemStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DonationRecorded"
      | "ItemCreated"
      | "ItemStatusChanged"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createItem",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "donations", values: [string]): string;
  encodeFunctionData(functionFragment: "getDonation", values: [string]): string;
  encodeFunctionData(functionFragment: "itemCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "items", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "recordDonation",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateItemStatus",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createItem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "donations", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDonation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "itemCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "items", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordDonation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateItemStatus",
    data: BytesLike
  ): Result;
}

export namespace DonationRecordedEvent {
  export type InputTuple = [
    donationId: string,
    donor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [donationId: string, donor: string, amount: bigint];
  export interface OutputObject {
    donationId: string;
    donor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ItemCreatedEvent {
  export type InputTuple = [id: BigNumberish, name: string, owner: AddressLike];
  export type OutputTuple = [id: bigint, name: string, owner: string];
  export interface OutputObject {
    id: bigint;
    name: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ItemStatusChangedEvent {
  export type InputTuple = [
    id: BigNumberish,
    status: BigNumberish,
    owner: AddressLike
  ];
  export type OutputTuple = [id: bigint, status: bigint, owner: string];
  export interface OutputObject {
    id: bigint;
    status: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SupplyChain extends BaseContract {
  connect(runner?: ContractRunner | null): SupplyChain;
  waitForDeployment(): Promise<this>;

  interface: SupplyChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  createItem: TypedContractMethod<
    [_name: string, _description: string, _quantity: BigNumberish],
    [void],
    "nonpayable"
  >;

  donations: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, bigint, boolean] & {
        donationId: string;
        donor: string;
        amount: bigint;
        purpose: string;
        timestamp: bigint;
        isUsed: boolean;
      }
    ],
    "view"
  >;

  getDonation: TypedContractMethod<
    [_donationId: string],
    [SupplyChain.DonationStructOutput],
    "view"
  >;

  itemCount: TypedContractMethod<[], [bigint], "view">;

  items: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, string, bigint] & {
        id: bigint;
        name: string;
        description: string;
        quantity: bigint;
        status: bigint;
        currentOwner: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  recordDonation: TypedContractMethod<
    [_donationId: string, _amount: BigNumberish, _purpose: string],
    [void],
    "nonpayable"
  >;

  updateItemStatus: TypedContractMethod<
    [_id: BigNumberish, _status: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createItem"
  ): TypedContractMethod<
    [_name: string, _description: string, _quantity: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "donations"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, bigint, boolean] & {
        donationId: string;
        donor: string;
        amount: bigint;
        purpose: string;
        timestamp: bigint;
        isUsed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDonation"
  ): TypedContractMethod<
    [_donationId: string],
    [SupplyChain.DonationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "itemCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "items"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, string, bigint] & {
        id: bigint;
        name: string;
        description: string;
        quantity: bigint;
        status: bigint;
        currentOwner: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordDonation"
  ): TypedContractMethod<
    [_donationId: string, _amount: BigNumberish, _purpose: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateItemStatus"
  ): TypedContractMethod<
    [_id: BigNumberish, _status: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DonationRecorded"
  ): TypedContractEvent<
    DonationRecordedEvent.InputTuple,
    DonationRecordedEvent.OutputTuple,
    DonationRecordedEvent.OutputObject
  >;
  getEvent(
    key: "ItemCreated"
  ): TypedContractEvent<
    ItemCreatedEvent.InputTuple,
    ItemCreatedEvent.OutputTuple,
    ItemCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ItemStatusChanged"
  ): TypedContractEvent<
    ItemStatusChangedEvent.InputTuple,
    ItemStatusChangedEvent.OutputTuple,
    ItemStatusChangedEvent.OutputObject
  >;

  filters: {
    "DonationRecorded(string,address,uint256)": TypedContractEvent<
      DonationRecordedEvent.InputTuple,
      DonationRecordedEvent.OutputTuple,
      DonationRecordedEvent.OutputObject
    >;
    DonationRecorded: TypedContractEvent<
      DonationRecordedEvent.InputTuple,
      DonationRecordedEvent.OutputTuple,
      DonationRecordedEvent.OutputObject
    >;

    "ItemCreated(uint256,string,address)": TypedContractEvent<
      ItemCreatedEvent.InputTuple,
      ItemCreatedEvent.OutputTuple,
      ItemCreatedEvent.OutputObject
    >;
    ItemCreated: TypedContractEvent<
      ItemCreatedEvent.InputTuple,
      ItemCreatedEvent.OutputTuple,
      ItemCreatedEvent.OutputObject
    >;

    "ItemStatusChanged(uint256,uint8,address)": TypedContractEvent<
      ItemStatusChangedEvent.InputTuple,
      ItemStatusChangedEvent.OutputTuple,
      ItemStatusChangedEvent.OutputObject
    >;
    ItemStatusChanged: TypedContractEvent<
      ItemStatusChangedEvent.InputTuple,
      ItemStatusChangedEvent.OutputTuple,
      ItemStatusChangedEvent.OutputObject
    >;
  };
}
